# Generated by Django 4.2.6 on 2023-10-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='pending',
            field=models.IntegerField(),
        ),
    ]
