# Generated by Django 4.2.6 on 2023-10-25 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_friendrequest_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitado', to=settings.AUTH_USER_MODEL),
        ),
    ]
